version: '3'

services:
  api:
    build: ./api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
      - public:/app/public
      - tmp:/app/tmp
      - log:/app/log
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  front:
    build: ./front
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    command: /bin/sh -c "yarn install && yarn serve"
volumes:
  mysql_data:
  bundle:
  public:
  tmp:
  log:
  node_modules:
